### ISSUE TITLE
[Bug]: Net8 installing OneSignalSDK.DotNet nuget

### ISSUE THREAD

**Issue by christosyiallourascy** [OneSignal/OneSignal-DotNet-SDK#121] opened 2024-09-09 08:38 UTC
### What happened?

I get the following exception when I tried to install the one signal net package to net8 project.

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Could not find a part of the path 'C:\Users\xxxxxxxxxxxxx\.nuget\packages\onesignalsdk.dotnet\5.2.1\res\ios\OneSignalFramework.xcframework\ios-arm64_x86_64-maccatalyst\OneSignalFramework.framework\Versions\A\Modules\OneSignalFramework.swiftmodule\x86_64-apple-ios-macabi.private.swiftinterface'.		

Can you please advise?

### Steps to reproduce?

```Markdown
1. Install nuget package from vs studio.
```

### What did you expect to happen?

package install.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mads195** [comment] 2024-09-10 08:21
This is the same as issue #108.

**Comment by emawby** [comment] 2024-09-10 19:11
closing as duplicate of #108

**Closed by emawby** 2024-09-10 19:11 UTC
